/**
 * Icon names → lucide components, for content that comes from the admin panel.
 *
 * The admin's icon picker offers a fixed list (`ICONS` in the backend's
 * `options.routes.ts`) and the server validates every saved value against it.
 * This map is the website's half of that contract and must stay in step: an
 * icon offered in the panel but missing here renders the fallback, which looks
 * like a bug to whoever picked it.
 *
 * Importing every lucide icon by name is not an option — the barrel is ~1,500
 * components and would land in the bundle. Naming them explicitly keeps
 * tree-shaking working, so only the icons actually offered ship.
 *
 * Distinct from `capability-icons.ts` and `tool-icons.ts`, which serve the
 * committed service and tool catalogues. This one serves CMS-authored records
 * (innovation cards, process steps, culture values, industries, FAQs).
 */
import {
  Activity,
  Award,
  BarChart3,
  Blocks,
  Bot,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Cable,
  ChartNoAxesCombined,
  CheckCircle2,
  CircuitBoard,
  Clock,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Eye,
  Factory,
  FileCode2,
  Fingerprint,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HeartPulse,
  HelpCircle,
  Images,
  Landmark,
  Layers,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  LineChart,
  Link2,
  ListOrdered,
  Lock,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Network,
  Newspaper,
  Package,
  PenTool,
  Plane,
  Quote,
  Repeat,
  Rocket,
  Scale,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Target,
  TestTube2,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CMS_ICONS: Record<string, LucideIcon> = {
  Activity,
  Award,
  BarChart3,
  Blocks,
  Bot,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Cable,
  ChartNoAxesCombined,
  CheckCircle2,
  CircuitBoard,
  Clock,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Eye,
  Factory,
  FileCode2,
  Fingerprint,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  // The panel offers this as "HandshakeIcon"; lucide exports it as `Handshake`.
  HandshakeIcon: Handshake,
  Heart,
  HeartPulse,
  HelpCircle,
  Images,
  Landmark,
  Layers,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  LineChart,
  Link2,
  ListOrdered,
  Lock,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Network,
  Newspaper,
  Package,
  PenTool,
  Plane,
  Quote,
  Repeat,
  Rocket,
  Scale,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Target,
  TestTube2,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap,
};

/**
 * Resolve an admin-supplied icon name. Never throws and never renders nothing:
 * a missing icon leaves a hole in the layout, which reads as broken, so an
 * unknown name falls back to a neutral shape and the grid stays intact.
 */
export function resolveIcon(name: string | null | undefined, fallback: LucideIcon = Sparkles): LucideIcon {
  if (!name) return fallback;
  return CMS_ICONS[name] ?? fallback;
}
