/**
 * Export the website's authored service and industry catalogs as JSON for the
 * admin API's seed.
 *
 *   npx tsx scripts/export-catalog.ts
 *
 * ## Why this exists
 *
 * `src/lib/services.ts` and `src/lib/industries.ts` hold the reviewed copy for
 * 15 services and 10 industries — the problem statements, approaches, paired
 * challenge/solution/outcome sets, and the cross-links between them. The admin
 * API's seed held five generic services and twelve one-line industries, every
 * string prefixed `[SAMPLE COPY]`. The two were never the same content.
 *
 * That did not matter while the pages read their own files. It matters the
 * moment the pages read the database: whichever copy the seed wrote is what a
 * visitor sees, and the sample copy would have replaced a page of reviewed
 * positioning with "Technology built for the realities of manufacturing."
 *
 * The obvious fix — paste the catalogs into the seed — creates the exact
 * duplication CLAUDE.md warns about: two copies of the same paragraphs, drifting
 * from the first edit. So the authored source stays here, in TypeScript, where
 * it is type-checked against `Service` and `Industry`, and this script derives
 * the seed's copy from it. Re-run it after editing either catalog; the JSON is a
 * build artifact of these files, not a second place to write copy.
 *
 * The seed still only ever *inserts* — an industry already in the database keeps
 * whatever an editor has since written. This moves the starting point, not
 * anyone's edits.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import { services } from "../src/lib/services";
import { industryCatalog } from "../src/lib/industries";
import { INDUSTRY_ICON_NAMES } from "../src/lib/industry-meta";
import { industryImages } from "../src/lib/preview-assets";
import { realEventGalleries } from "../src/lib/real-assets";
import {
  awards,
  clients,
  faqs,
  processPhases,
  processSteps,
  testimonials,
} from "../src/lib/content";
import { cultureValues, growthOpportunities } from "../src/lib/careers-content";
import { impactStories, nav, navCta } from "../src/lib/site";
import { blogPosts } from "../src/lib/blog";

/**
 * How the rich-text columns separate paragraphs — a blank line, which is what
 * `toParagraphs` on the website splits back out. Named rather than inlined so
 * the two escapes cannot be mistaken for one.
 */
const PARAGRAPH_BREAK = "\n\n";

/** Where the API's seed reads it from. The two projects are siblings on disk. */
const DESTINATION = path.resolve(
  process.cwd(),
  "../sumago-website-backend/src/db/catalog.json",
);

const catalog = {
  /*
   * A note to whoever opens the JSON wondering whether to edit it. Kept as a
   * data key rather than a comment because JSON has none.
   */
  $generated:
    "Generated by the website's scripts/export-catalog.ts from src/lib/services.ts and " +
    "src/lib/industries.ts. Do not edit by hand — edit those files and re-run the script.",

  services: services.map((service) => ({
    name: service.name,
    slug: service.slug,
    icon: service.icon,
    phase: service.phase,
    blurb: service.blurb,
    problem: service.problem,
    summary: service.summary,
    approach: service.approach,
    deliverables: service.deliverables,
    outcomes: service.outcomes,
    technologies: service.technologies,
    tools: service.tools,
    // `whoFor` and `stories` are optional on the type; the column is NOT NULL
    // with an empty default, so an absent value has to become an empty list
    // here rather than a null the insert would reject.
    whoFor: service.whoFor ?? [],
    stories: service.stories ?? [],
  })),

  industries: industryCatalog.map((industry) => ({
    name: industry.name,
    slug: industry.slug,
    /*
     * The icon *name*, not a component — the column is a string chosen from the
     * admin's fixed icon list, and `industry-meta.ts` keeps the committed map
     * in that same currency so it can travel here unchanged.
     */
    icon: INDUSTRY_ICON_NAMES[industry.slug] ?? "Boxes",
    blurb: industry.blurb,
    summary: industry.summary,
    problem: industry.problem,
    approach: industry.approach,
    challenges: industry.challenges,
    solutions: industry.solutions,
    outcomes: industry.outcomes,
    services: industry.services,
    stories: industry.stories ?? [],
    /*
     * The card still. `image` is required in the admin registry, and an
     * industry published without one would render an empty tile on
     * /industries — so the preview asset the page already uses travels with
     * the record. [REAL ASSET NEEDED] before launch (docs/17).
     */
    image: industryImages[industry.slug] ?? null,
  })),

  /*
   * The supporting lists.
   *
   * Each of these had a handful of sample rows in the API's seed against a
   * complete, reviewed list here — three client logos against nineteen, three
   * culture values against six. Wiring the pages to the database without this
   * would have been a visible regression: a logo marquee with three marks in
   * it, and a values grid half empty.
   */
  clients: clients.map((client) => ({
    name: client.name,
    logo: client.logo ?? null,
    /*
     * Two classifications, deliberately. `type` is the geography the admin
     * panel filters and reports on; `segment` is the constituency the About
     * page's trust wall groups by. Deriving one from the other loses the
     * distinction that matters — "enterprise" and "growth" are both Domestic.
     */
    type: client.segment === "government" ? "Government" : "Domestic",
    segment: client.segment,
  })),

  awards: awards.map((award) => ({
    title: award.title,
    short: award.short,
    detail: award.detail,
    year: award.year,
    kind: award.kind,
    icon: award.icon,
    // Optional on the committed type and nullable in the column: a certification
    // has a scope and a standing, an award has a recipient, and neither has the
    // other's fields.
    tagline: award.tagline ?? null,
    org: award.org ?? null,
    scope: award.scope ?? null,
    standing: award.standing ?? null,
    recipient: award.recipient ?? null,
  })),

  /* `name` travels because consent is personal and the record has to say who
     gave it — the admin panel shows it. No page renders it; the attribution a
     visitor sees is `company` and `role`. */
  testimonials: testimonials.map((testimonial) => ({
    quote: testimonial.quote,
    name: testimonial.name,
    role: testimonial.role,
    company: testimonial.company,
    rating: testimonial.rating,
    accent: testimonial.accent,
  })),

  faqs: faqs.map((faq) => ({ q: faq.q, a: faq.a })),

  processSteps: processSteps.map((step) => ({
    title: step.title,
    description: step.description,
    icon: step.icon,
    phase: step.phase,
  })),

  processPhases: processPhases.map((phase) => ({
    name: phase.name,
    tagline: phase.tagline,
  })),

  cultureValues: cultureValues.map((value) => ({
    icon: value.icon,
    title: value.title,
    description: value.description,
  })),

  growthOpportunities: growthOpportunities.map((item) => ({
    icon: item.icon,
    title: item.title,
    description: item.description,
  })),

  /*
   * The header mega-menu and its CTA.
   *
   * A singleton rather than a list, and the one module where a thin record is
   * actively harmful: the header renders whatever it holds, so a navigation row
   * carrying one group of one link replaces an eleven-link menu with a stub.
   * Seeding the committed structure means the panel starts from the site that
   * ships and an editor edits *that*.
   *
   * The footer columns stay out of it deliberately — the footer's service and
   * industry lists are generated from those modules, and its two remaining
   * columns are routes, not content (see `site-footer.tsx`).
   */
  /*
   * Per-page SEO, seeded from the descriptions the pages themselves ship with.
   *
   * The seed used to write "[SAMPLE COPY] Replace with a written description"
   * into all thirteen records. Harmless while nothing read them; the moment
   * `generateMetadata` layered the panel over the page, that placeholder became
   * the `<meta name="description">` a search engine indexes — sample copy
   * *overriding* reviewed copy, which is worse than having no record at all.
   *
   * These are the same strings the page exports, so the record starts as a
   * faithful copy of what ships and an editor edits from there. Titles stay as
   * the seed wrote them: they are written for search results, where the brand
   * belongs in the string, and the page titles are not.
   */
  /*
   * Blog posts and success stories.
   *
   * Both are still flagged preview content (docs/17) — the first paragraph of
   * each carries `[SAMPLE COPY]`, and a production build gate blocks them. They
   * are exported anyway because the API seed wrote something *worse*: a single
   * line reading "Replace this body with the real post before launch". Once the
   * pages read the database, that one line replaced four paragraphs of drafted
   * copy. Carrying the committed bodies across keeps the two in step and keeps
   * the flag visible where it belongs — in the copy, for whoever replaces it.
   */
  /*
   * Every column the seed writes, not just the body. The seed used to carry its
   * own hardcoded list of titles, excerpts, tags and dates beside the bodies it
   * read from here — two half-copies of the same posts, which is how the
   * database ended up describing a different set of articles than the website
   * shipped. The post list lives in `src/lib/blog.ts` and nowhere else.
   *
   * `featured` is the newest post: /blog leads with the first record the API
   * returns, and the API orders featured-first.
   */
  blogPosts: blogPosts.map((post, index) => ({
    slug: post.slug,
    title: post.title,
    excerpt: post.excerpt,
    // Blocks join with a blank line — the Markdown convention the API stores
    // and `parseMarkdown` splits back out.
    body: post.body.join(PARAGRAPH_BREAK),
    cover: post.cover,
    category: post.category,
    tags: post.tags,
    author: post.author,
    date: post.date,
    readingTime: post.readingTime,
    metaTitle: post.metaTitle,
    metaDescription: post.metaDescription,
    featured: index === 0,
  })),

  /*
   * Every column the seed writes, for the same reason as `blogPosts` above: the
   * seed used to hold its own list of titles, industries, regions and
   * technologies beside the bodies it read from here, and the two drifted — all
   * four stories ended up filed under one industry in the database because the
   * seed's own list named sectors the industries table does not have.
   */
  successStories: impactStories.map((story) => ({
    slug: story.slug,
    title: story.title,
    summary: story.summary,
    category: story.category,
    industry: story.industry,
    region: story.region,
    coverImage: story.cover,
    technologies: [...story.tech],
    metaTitle: "metaTitle" in story ? story.metaTitle : "",
    metaDescription: "metaDescription" in story ? story.metaDescription : "",
    // The template reads four named sections; the committed body is an ordered
    // list of blocks, so the first three map across and anything after the
    // third folds into the closing impact paragraph.
    background: story.body[0] ?? "",
    challenge: story.body[1] ?? "",
    solution: story.body[2] ?? "",
    impact:
      story.body.slice(3).join(PARAGRAPH_BREAK) ||
      story.body[story.body.length - 1] ||
      "",
  })),

  seoDescriptions: {
    "/": "Sumago Infotech is a technology consulting, digital transformation and product engineering partner — ISO 9001:2015 and CMMI Level 5 certified, since 2013.",
    "/about":
      "The story, mantra, values, recognition, and people behind Sumago — a strategic technology partner since 2013.",
    "/team": "Founder-led since 2013 — the leadership and 70+ specialists behind Sumago's work.",
    "/life-at-sumago":
      "The culture behind the work — continuous learning, real ownership, and a team that enjoys solving hard problems.",
    "/careers":
      "Open roles at Sumago — engineering, design and delivery positions for people who like solving real problems.",
    "/solutions":
      "The full range of services across the technology lifecycle — from consulting and strategy to design, engineering, and long-term support.",
    "/industries":
      "Domain expertise across ten industries — logistics, manufacturing, healthcare, banking, education, retail, government, hospitality, real estate, and professional services.",
    "/impact":
      "Client transformation, measured in business outcomes — the work behind 700+ delivered projects.",
    "/innovation":
      "Applied AI, automation and data intelligence — chatbots and assistants, voice and language AI, workflow automation, and analytics built into everyday decisions.",
    "/blog": "Engineering notes, product thinking, and perspective from the Sumago team.",
    "/contact":
      "Start a conversation with Sumago — talk to an expert or schedule a meeting. Offices across Nashik and Pune.",
    "/privacy": "How Sumago Infotech handles the information you share through this website.",
    "/terms": "The terms that govern use of the Sumago Infotech website and services.",
  } as Record<string, string>,

  navigation: {
    groups: nav.map((group) => ({
      label: group.label,
      items: group.items.map((item) => ({
        label: item.label,
        href: item.href,
        description: item.description,
      })),
    })),
    ctaLabel: navCta.label,
    ctaHref: navCta.href,
  },

  eventGalleries: realEventGalleries.map((gallery) => ({
    key: gallery.key,
    title: gallery.title,
    // Each photograph carries the alt written against it in the image manifest.
    // These are real, identifiable events, so a per-category caption would be a
    // downgrade rather than a safe default.
    images: gallery.images.map((image) => ({ url: image.src, alt: image.alt })),
  })),
};

// Wrapped rather than run at the top level: the website package is CommonJS,
// where a top-level `await` will not compile.
async function main(): Promise<void> {
  const missingImages = catalog.industries.filter((industry) => !industry.image);
  if (missingImages.length > 0) {
    // Not fatal — the seed falls back — but it is how a new industry silently
    // ends up as the one tile on the page with no picture.
    console.warn(
      `[export-catalog] no image mapped for: ${missingImages.map((i) => i.slug).join(", ")}`,
    );
  }

  await writeFile(DESTINATION, `${JSON.stringify(catalog, null, 2)}\n`, "utf8");

  const counts = Object.entries(catalog)
    .flatMap(([key, value]) => (Array.isArray(value) ? [`${value.length} ${key}`] : []))
    .join(", ");

  console.info(`[export-catalog] wrote ${counts} to ${DESTINATION}`);
}

main().catch((error: unknown) => {
  console.error("[export-catalog] failed:", error);
  process.exit(1);
});
